parameters:
- name: SignArtifacts
  type: boolean
  default: false

resources:
  repositories:
  - repository: internal-templates
    type: github
    name: xamarin/yaml-templates
    endpoint: xamarin
    ref: refs/heads/main

stages:
- stage: Publish
  dependsOn: Build
  condition: and(eq(dependencies.Build.result, 'Succeeded'), or(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), eq('${{ parameters.SignArtifacts }}', 'true'))) # only sign the packages when running on Windows, and using the private server which has the certificates
  jobs:
  - template: sign-artifacts/jobs/v2.yml@internal-templates
    parameters:
      usePipelineArtifactTasks: true
      use1ESTemplate: true
      signListPath: 'SignList.xml'
