#!/bin/bash -e
if [ -z "$HOSTOS" ]; then
    HOSTOS=$(uname)
fi
ARCH=${ARCH:-64}
install -d -m 755 build/$HOSTOS/$ARCH
cd build/$HOSTOS/$ARCH
if [ -e "$TOOLCHAIN_FILE" ]; then
    ARGS=-DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE
fi
cmake -GNinja -DCMAKE_MAKE_PROGRAM=ninja -DBUILD_SHARED_LIBS=ON -DOPENSSL_USE_STATIC_LIBS=ON -DENABLE_BZIP2=OFF -DENABLE_LZMA=OFF $ARGS ../../../external/libzip
ninja -v
cd ../../..