#!/bin/bash -e
if [ -z "$HOSTOS" ]; then
    HOSTOS=$(uname)
fi
install -d -m 755 build/$HOSTOS
cd build/$HOSTOS
cmake -GNinja -DCMAKE_MAKE_PROGRAM=ninja -DBUILD_SHARED_LIBS=ON ../../external/libzip
ninja
cd ../..