parameters:
- name: use1ESTemplate
  type: boolean
  default: true
- name: publishTaskPrefix
  type: string
  default: 1ES.

stages:
- stage: Test
  dependsOn: Build
  variables:
    DotNetCoreVersion: 3.1.201
    DotNetVersion: 8.0.419
  jobs:
  - job: testlinux
    displayName: 'Test Linux'
    ${{ if eq(parameters.use1ESTemplate, true) }}:
      pool:
        name: AzurePipelines-EO
        image: $(LinuxPoolImage1ESPT)
        os: linux
    ${{ else }}:
      pool:
        name: Azure Pipelines
        vmImage: $(LinuxPoolImageHosted)
    steps:
    - template: /yaml-templates/use-dot-net.yaml
      parameters:
        version: $(DotNetCoreVersion)
    - template: /yaml-templates/use-dot-net.yaml
      parameters:
        version: $(DotNetVersion)
    - task: DownloadPipelineArtifact@2
      displayName: download artifacts
      inputs:
        artifactName: nuget
        downloadPath: $(Build.SourcesDirectory)
    - script: dotnet build LibZipSharp.UnitTest/LibZipSharp.UnitTest.csproj -c Release -p:ReferenceNuget=True -v:diag
      displayName: 'Build solution LibZipSharp.UnitTest/LibZipSharp.UnitTest.csproj'
    - script: dotnet test LibZipSharp.UnitTest/LibZipSharp.UnitTest.csproj -c Release -p:ReferenceNuget=True -v:diag --logger trx --results-directory $(Build.SourcesDirectory)/TestResults
      displayName: 'Run Unit tests for .net'
    - task: PublishTestResults@2
      displayName: Publish test results
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '$(Build.SourcesDirectory)/TestResults/**/*.trx'

  - job: testmacos
    displayName: 'Test MacOS'
    pool:
      name: Azure Pipelines
      vmImage: macOS-14
      os: macOS
    steps:
    - template: /yaml-templates/use-dot-net.yaml
      parameters:
        version: $(DotNetCoreVersion)
    - template: /yaml-templates/use-dot-net.yaml
      parameters:
        version: $(DotNetVersion)
    - task: DownloadPipelineArtifact@2
      displayName: download artifacts
      inputs:
        artifactName: nuget
        downloadPath: $(Build.SourcesDirectory)
    - script: dotnet build LibZipSharp.UnitTest/LibZipSharp.UnitTest.csproj -c Release -p:ReferenceNuget=True -v:diag
      displayName: 'Build solution LibZipSharp.UnitTest/LibZipSharp.UnitTest.csproj'
    - script: dotnet test LibZipSharp.UnitTest/LibZipSharp.UnitTest.csproj -c Release -p:ReferenceNuget=True -v:diag --logger trx --results-directory $(Build.SourcesDirectory)/TestResults
      displayName: 'Run Tests under .net'
    - task: PublishTestResults@2
      displayName: Publish test results
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '$(Build.SourcesDirectory)/TestResults/**/*.trx'

  - job: testwindows
    displayName: 'Test Windows'
    ${{ if eq(parameters.use1ESTemplate, true) }}:
      pool:
        name: AzurePipelines-EO
        image: $(WindowsPoolImage1ESPT)
        os: windows
    ${{ else }}:
      pool:
        name: Azure Pipelines
        vmImage: $(WindowsPoolImageHosted)
    steps:
    - template: /yaml-templates/use-dot-net.yaml
      parameters:
        version: $(DotNetCoreVersion)
    - template: /yaml-templates/use-dot-net.yaml
      parameters:
        version: $(DotNetVersion)
    - task: DownloadPipelineArtifact@2
      displayName: download artifacts
      inputs:
        artifactName: nuget
        downloadPath: $(Build.SourcesDirectory)
    - script: dotnet build LibZipSharp.UnitTest/LibZipSharp.UnitTest.csproj -c Release -p:ReferenceNuget=True -v:diag
      displayName: 'Build solution LibZipSharp.UnitTest/LibZipSharp.UnitTest.csproj'
    - script: dotnet test LibZipSharp.UnitTest/LibZipSharp.UnitTest.csproj -c Release -p:ReferenceNuget=True -v:diag --logger trx --results-directory $(Build.SourcesDirectory)/TestResults
      displayName: 'Run Tests LibZipSharp.UnitTest/LibZipSharp.UnitTest.csproj'
    - task: PublishTestResults@2
      displayName: Publish test results
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '$(Build.SourcesDirectory)/TestResults/**/*.trx'
