//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Tools.Zip.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.Tools.Zip.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive destination path must not be empty..
        /// </summary>
        internal static string DestinationMustNotBeEmpty {
            get {
                return ResourceManager.GetString("DestinationMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while reading the file &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorReadingFile_file {
            get {
                return ResourceManager.GetString("ErrorReadingFile_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while reading the stream..
        /// </summary>
        internal static string ErrorReadingStream {
            get {
                return ResourceManager.GetString("ErrorReadingStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos; is an instance of &apos;{1}&apos; instead of the expected type &apos;{2}&apos;..
        /// </summary>
        internal static string ExpectedAnInstanceOf_string_type {
            get {
                return ResourceManager.GetString("ExpectedAnInstanceOf_string_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the symbolic link &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string FailedToReadSymLink_link_error {
            get {
                return ResourceManager.GetString("FailedToReadSymLink_link_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: failed to set owner of entry &apos;{0}&apos; ({1}:{2})..
        /// </summary>
        internal static string FailedToSetOwner_entry_error_oserror {
            get {
                return ResourceManager.GetString("FailedToSetOwner_entry_error_oserror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: failed to stat file &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string FailedToStatFile_file_error {
            get {
                return ResourceManager.GetString("FailedToStatFile_file_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file already exists..
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; could not be opened..
        /// </summary>
        internal static string FileCouldNotBeOpened_file {
            get {
                return ResourceManager.GetString("FileCouldNotBeOpened_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; does not exist and file creation wasn&apos;t requested..
        /// </summary>
        internal static string FileDoesNotExist_file {
            get {
                return ResourceManager.GetString("FileDoesNotExist_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; does not support seeking..
        /// </summary>
        internal static string FileDoesNotSupportSeeking_file {
            get {
                return ResourceManager.GetString("FileDoesNotSupportSeeking_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} failed consistency checks..
        /// </summary>
        internal static string FileFailedConsistencyChecks_file {
            get {
                return ResourceManager.GetString("FileFailedConsistencyChecks_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is not a ZIP archive..
        /// </summary>
        internal static string FileIsNotAZip_file {
            get {
                return ResourceManager.GetString("FileIsNotAZip_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; already exists..
        /// </summary>
        internal static string FilePathAlreadyExists_file {
            get {
                return ResourceManager.GetString("FilePathAlreadyExists_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing files of type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string FileTypeNotSupported_filetype {
            get {
                return ResourceManager.GetString("FileTypeNotSupported_filetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an instance of &apos;{1}&apos;, which is not a valid entry type. The expected type is &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidEntryType_string_type {
            get {
                return ResourceManager.GetString("InvalidEntryType_string_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be an instance of &apos;{1}&apos;..
        /// </summary>
        internal static string MustBeAnInstanceOf_string_type {
            get {
                return ResourceManager.GetString("MustBeAnInstanceOf_string_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must not be null or empty..
        /// </summary>
        internal static string MustNotBeNullOrEmpty_string {
            get {
                return ResourceManager.GetString("MustNotBeNullOrEmpty_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to libzip failed due to an out of memory error..
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream could not be opened..
        /// </summary>
        internal static string StreamCouldNotBeOpened {
            get {
                return ResourceManager.GetString("StreamCouldNotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not exist and file creation wasn&apos;t requested..
        /// </summary>
        internal static string StreamDoesNotExist {
            get {
                return ResourceManager.GetString("StreamDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream does not support seeking..
        /// </summary>
        internal static string StreamDoesNotSupportSeeking {
            get {
                return ResourceManager.GetString("StreamDoesNotSupportSeeking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream failed consistency checks..
        /// </summary>
        internal static string StreamFailedConsistencyChecks {
            get {
                return ResourceManager.GetString("StreamFailedConsistencyChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is not a ZIP archive..
        /// </summary>
        internal static string StreamIsNotAZip {
            get {
                return ResourceManager.GetString("StreamIsNotAZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to determine type of the file &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToDetermineFileType_file {
            get {
                return ResourceManager.GetString("UnableToDetermineFileType_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected libzip error: {0}..
        /// </summary>
        internal static string UnexpectedLibZipError_error {
            get {
                return ResourceManager.GetString("UnexpectedLibZipError_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an instance of &apos;{1}&apos;, which is not a valid options type. The expected type is &apos;{2}&apos;..
        /// </summary>
        internal static string UnexpectedOptionsType_string_type_type {
            get {
                return ResourceManager.GetString("UnexpectedOptionsType_string_type_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a supported file type. Only regular files, directories, and symbolic links are currently supported..
        /// </summary>
        internal static string UnsupportedPermission_UnixExternalPermissions {
            get {
                return ResourceManager.GetString("UnsupportedPermission_UnixExternalPermissions", resourceCulture);
            }
        }
    }
}
